package gov.uspto.session.model;

public enum ReauthReason {
    SESSION_TIMEOUT,
    IDLE_TIMEOUT,
    PRIVILEGE_ESCALATION,
    ROLE_CHANGE,
    SECURITY_ATTRIBUTE_CHANGE,
    SENSITIVE_OPERATION,
    IP_ADDRESS_CHANGE,
    USER_AGENT_CHANGE,
    CONCURRENT_SESSION_DETECTED,
    ORGANIZATION_POLICY,
    MANUAL_REQUEST,
    SECURITY_EVENT
}
